name: monster_hunter
description: App modulare e scalabile su Monster Hunter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_slidable: ^3.0.1
  photo_view: ^0.14.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  animations: ^2.0.8
  flutter_haptic_feedback: ^1.0.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/mostri/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1C1E20"
  adaptive_icon_foreground: "assets/icons.png"

